volumes:
  lgsm:

services:
  lgsm:
    # Limites (Rust precisa de 4G)
    cpu_count: 2
    mem_limit: 4g

    init: true
    user: root
    image: gameservermanagers/linuxgsm-docker
    restart: always

    command:
      - /bin/bash
      - -exc
      - |
        # MAIN
        apt-get update
        apt-get install -y dos2unix rsync sudo vim nano libgdiplus python3.8-venv lib32z1

        # grant temporary sudo access for initial setup
        echo 'linuxgsm  ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/lgsm

        lgsm_uid="$$(id -u linuxgsm)"
        lgsm_gid="$$(id -g linuxgsm)"
        if [ ! "$$lgsm_uid" = 1000 ]; then
          sed -i "s/:$$lgsm_uid:$$lgsm_gid:/:1000:1000:/" /etc/passwd
          sed -i "s/:$$lgsm_gid:/:1000:/" /etc/group
        fi

        if [ ! "$$(stat -c '%U' /home/linuxgsm)" = linuxgsm ]; then
          chown -R linuxgsm: /home/linuxgsm
        fi
        if [ ! "$$(stat -c '%U' /custom-maps)" = linuxgsm ]; then
          chown -R linuxgsm: /custom-maps
        fi

        python3 -m venv /home/linuxgsm/.venv
        grep -F .venv ~linuxgsm/.bash_profile || echo 'source /home/linuxgsm/.venv/bin/activate' > ~linuxgsm/.bash_profile
        grep -F .venv ~linuxgsm/.bashrc || echo 'source /home/linuxgsm/.venv/bin/activate' > ~linuxgsm/.bashrc
        if [ ! "$$(stat -c '%U' /home/linuxgsm/.venv)" = linuxgsm ]; then
          chown -R linuxgsm: /home/linuxgsm/.venv
        fi

        chown linuxgsm: /home/linuxgsm /home/linuxgsm/serverfiles /home/linuxgsm/serverfiles/oxide || true
        chown -R linuxgsm: /home/linuxgsm/serverfiles/oxide/config || true

        rm -f ~linuxgsm/linuxgsm.sh
        su - linuxgsm -c "LINUX_GSM_VERSION=\"${LINUX_GSM_VERSION:-v20.4.1}\" /utils/custom-rust-server.sh"

    volumes:
      - lgsm:/home/linuxgsm
      - ./mod-configs/:/home/linuxgsm/serverfiles/oxide/config/:rw
      - ./custom-mods/:/custom-plugins/:ro
      - ./custom-maps/:/custom-maps/:rw
      - ./harmony-mods:/home/linuxgsm/serverfiles/HarmonyMods
      - ./harmony-config:/home/linuxgsm/serverfiles/HarmonyConfig
      - ./utils/:/utils/:ro
      - ./rust-environment.sh:/rust-environment.sh:ro

    ports:
      - "28015:28015/udp"   # Porta de jogo
      - "28016:28016/tcp"   # Porta RCON/WebRCON
      - "28082:28082/udp"   # Query/Steam
      # - "8000:8000/tcp"   # painel opcional

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    healthcheck:
      test: ["CMD", "pgrep", "RustDedicated"]
      interval: 10s
      retries: 3
      start_period: 20m
