volumes:
  lgsm:

services:
  lgsm:
    # Limites (Rust precisa de 4G+)
    cpu_count: 2
    mem_limit: 8g

    init: true
    user: root
    image: gameservermanagers/linuxgsm-docker
    restart: always

    command:
      - /bin/bash
      - -exc
      - |
        # ================
        # PRE-BOOT MAIN
        # ================
        apt-get update
        apt-get install -y dos2unix rsync sudo vim nano libgdiplus python3.8-venv lib32z1

        # grant temporary sudo access for initial setup
        echo 'linuxgsm  ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/lgsm

        # Normaliza UID/GID do usuário linuxgsm (esperado 1000)
        lgsm_uid="$(id -u linuxgsm)"
        lgsm_gid="$(id -g linuxgsm)"
        if [ ! "$lgsm_uid" = 1000 ]; then
          sed -i "s/:$lgsm_uid:$lgsm_gid:/:1000:1000:/" /etc/passwd
          sed -i "s/:$lgsm_gid:/:1000:/" /etc/group
        fi

        # Garante que diretórios existem (alguns são bind mounts do host)
        mkdir -p \
          /home/linuxgsm \
          /home/linuxgsm/serverfiles/oxide/plugins \
          /home/linuxgsm/serverfiles/oxide/config \
          /custom-maps \
          /home/linuxgsm/serverfiles/HarmonyMods \
          /home/linuxgsm/serverfiles/HarmonyConfig \
          /utils

        # Corrige ownership dos diretórios principais
        chown -R linuxgsm: /home/linuxgsm || true
        chown -R linuxgsm: /custom-maps || true
        chown -R linuxgsm: /home/linuxgsm/serverfiles || true

        # Cria e ativa venv do linuxgsm
        python3 -m venv /home/linuxgsm/.venv
        grep -F ".venv/bin/activate" ~linuxgsm/.bash_profile >/dev/null 2>&1 || echo 'source /home/linuxgsm/.venv/bin/activate' > ~linuxgsm/.bash_profile
        grep -F ".venv/bin/activate" ~linuxgsm/.bashrc >/dev/null 2>&1 || echo 'source /home/linuxgsm/.venv/bin/activate' > ~linuxgsm/.bashrc
        chown -R linuxgsm: /home/linuxgsm/.venv || true

        # ------------------------------
        # CORREÇÃO AUTOMÁTICA DE DONO
        # (resolve 'Ownership issues found')
        # ------------------------------
        # Plugins e configs (inclusive arquivos trazidos do host via bind mount)
        chown -R linuxgsm: /home/linuxgsm/serverfiles/oxide || true
        find /home/linuxgsm/serverfiles/oxide -type d -exec chmod 755 {} \; || true
        find /home/linuxgsm/serverfiles/oxide -type f -exec chmod 644 {} \; || true

        # Utils (scripts custom) e harmonys
        chown -R linuxgsm: /utils /home/linuxgsm/serverfiles/HarmonyMods /home/linuxgsm/serverfiles/HarmonyConfig || true
        find /utils -type f -name "*.sh" -exec dos2unix {} \; -exec chmod +x {} \; || true

        # Remove script antigo e executa bootstrap do servidor
        rm -f ~linuxgsm/linuxgsm.sh
        su - linuxgsm -c "LINUX_GSM_VERSION=\"${LINUX_GSM_VERSION:-v20.4.1}\" /utils/custom-rust-server.sh"

    volumes:
      - lgsm:/home/linuxgsm
      - ./mod-configs/:/home/linuxgsm/serverfiles/oxide/config/:rw
      - ./oxide-plugins:/home/linuxgsm/serverfiles/oxide/plugins:rw   # <-- PERSISTE PLUGINS
      - ./custom-mods/:/custom-plugins/:ro
      - ./custom-maps/:/custom-maps/:rw
      - ./harmony-mods:/home/linuxgsm/serverfiles/HarmonyMods
      - ./harmony-config:/home/linuxgsm/serverfiles/HarmonyConfig
      - ./utils/:/utils/:ro
      - ./rust-environment.sh:/rust-environment.sh:ro

    ports:
      - "28015:28015/udp"   # Porta do jogo
      - "28016:28016/tcp"   # RCON/WebRCON
      - "28082:28082/udp"   # Query/Steam

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    healthcheck:
      test: ["CMD", "pgrep", "RustDedicated"]
      interval: 10s
      retries: 3
      start_period: 20m
